replicaCount: 1

image:
  repository: ghcr.io/komari-monitor/komari
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 25774

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: komari.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

nodeSelector: {}

tolerations: []

affinity: {}

env:
  ADMIN_USERNAME: ""
  ADMIN_PASSWORD: ""

persistentVolume:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  storageClassName: ""
  existingClaim: ""
  mountPath: /app/data

statefulSet:
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
